name: news_app
description: "A new Flutter project. App that will just reflect basic understanding of flutter"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # Date format:
  intl: ^0.19.0
  # Data base
  floor: ^1.5.0
  # make request to API
  retrofit: ^4.4.1
  # Hooks
  flutter_hooks: ^0.20.5

  #cached image
  cached_network_image: ^3.2.0
  equatable: ^2.0.5
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.4
  floor_generator: ^1.5.0
  build_runner: ^2.4.13


flutter:

  uses-material-design: true

